### PR TITLE
Face Detection

### PR DESCRIPTION
**Pull request by Rohitm619**

### CODE REVIEW

**Comment by friskycodeur** [comment]
Looks good @Rohitm619 , can you update the readme as per the [Sample Readme File](https://github.com/friskycodeur/curated-project-list/blob/main/resources/sample_readme.md)

**Review by friskycodeur — CHANGES_REQUESTED** [review]
Update the readme file as per the [Sample readme file](https://github.com/friskycodeur/curated-project-list/blob/main/resources/sample_readme.md)

**Review by Rohitm619 — COMMENTED** [review]
Updated readme.md

**Comment by Rohitm619** [comment]
@friskycodeur Please consider the changes in readme.md

**Review by friskycodeur — APPROVED** [review]

**Pull request merged**
